# Generated by Django 5.2.7 on 2026-09-25 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialSearchPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text="Opaque filter payload, camelCase as the search page's query params spell it (searchTitle, trialType, phase, …). Not validated against a schema — see the class docstring.")),
                ('weights_wizard_offered', models.BooleanField(default=False, help_text='Whether this identity has been offered the weights wizard. Offered once: a reader who dismissed it has answered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(help_text='The verified identity these preferences belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='trial_search_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'trial search preferences',
                'db_table': 'user_state_trial_search_preferences',
            },
        ),
    ]
