# Generated by Django 5.2.7 on 2026-06-12 19:03
#
# NOTE: when TRIALS_DATABASE_URL is set (split-DB deploy), exact/db_router.py
# returns allow_migrate=False for the `trials` app, so this migration is
# recorded as applied but its AddConstraint DDL is NOT run against the external
# trials DB. Apply the CHECK constraints there manually via
# trials/migrations/sql/0007_trial_score_check_constraints.sql. The AlterField
# steps are no-op DDL (field validators + help_text only).

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0006_trial_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='benefit_score',
            field=models.PositiveIntegerField(blank=True, help_text='Benefit on a 0–20 scale (higher = more benefit).', null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='trial',
            name='patient_burden_score',
            field=models.PositiveIntegerField(blank=True, help_text='Patient burden on a 0–20 scale (higher = more burden).', null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='trial',
            name='risk_score',
            field=models.PositiveIntegerField(blank=True, help_text='Risk on a 0–20 scale (higher = more risk).', null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddConstraint(
            model_name='trial',
            constraint=models.CheckConstraint(condition=models.Q(('benefit_score__isnull', True), models.Q(('benefit_score__gte', 0), ('benefit_score__lte', 20)), _connector='OR'), name='trials_benefit_score_0_20'),
        ),
        migrations.AddConstraint(
            model_name='trial',
            constraint=models.CheckConstraint(condition=models.Q(('patient_burden_score__isnull', True), models.Q(('patient_burden_score__gte', 0), ('patient_burden_score__lte', 20)), _connector='OR'), name='trials_patient_burden_score_0_20'),
        ),
        migrations.AddConstraint(
            model_name='trial',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__isnull', True), models.Q(('risk_score__gte', 0), ('risk_score__lte', 20)), _connector='OR'), name='trials_risk_score_0_20'),
        ),
    ]
