# Generated by Django 5.2.7 on 2026-06-20 15:50

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0007_alter_trial_benefit_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighRiskMclCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.TextField(db_index=True, unique=True)),
                ("title", models.TextField(db_index=True, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="trial",
            name="high_risk_mcl_criteria_excluded",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="high_risk_mcl_criteria_min_count",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="high_risk_mcl_criteria_required",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="high_risk_mcl_criteria_sufficient_any",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["high_risk_mcl_criteria_required"],
                name="idx_hr_mcl_required_gin",
                opclasses=["jsonb_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["high_risk_mcl_criteria_excluded"],
                name="idx_hr_mcl_excluded_gin",
                opclasses=["jsonb_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["high_risk_mcl_criteria_sufficient_any"],
                name="idx_hr_mcl_sufficient_gin",
                opclasses=["jsonb_ops"],
            ),
        ),
    ]
