# Generated by Django 5.2.7 on 2026-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0008_highriskmclcriteria_and_more"),
    ]

    operations = [
        # Rename (not remove+add) so any existing column data is preserved.
        migrations.RenameField(
            model_name="trial",
            old_name="lesion_size_mcl_max",
            new_name="largest_lesion_size_max",
        ),
        migrations.RenameField(
            model_name="trial",
            old_name="lesion_size_mcl_min",
            new_name="largest_lesion_size_min",
        ),
        migrations.AddField(
            model_name="trial",
            name="p53_ihc_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trial",
            name="p53_ihc_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
