# Generated by Django 5.2.7 on 2026-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0009_trial_largest_lesion_size_rename_and_p53_ihc"),
    ]

    operations = [
        migrations.AddField(
            model_name="trial",
            name="haematological_adequacy_required",
            field=models.BooleanField(
                blank=True,
                help_text="Is a haematological adequacy required?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trial",
            name="hepatic_adequacy_required",
            field=models.BooleanField(
                blank=True, help_text="Is a hepatic adequacy required?", null=True
            ),
        ),
    ]
