# Generated by Django 5.2.7 on 2026-06-22 13:30

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0010_trial_haematological_adequacy_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapy",
            name="omop_concept_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="OMOP concept_id for this code (pinned CTOMOP release); null when the regimen has no clean standard concept and is expanded into its components/classes at backfill. Source for the trial omop_* columns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="therapycomponent",
            name="omop_concept_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="OMOP concept_id for this drug component (pinned CTOMOP release); null when unmapped. Source for the trial omop_therapy_components_* columns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="therapycomponentcategory",
            name="omop_concept_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="OMOP concept_id for this drug class (pinned CTOMOP release); null when unmapped. Source for the trial omop_therapy_types_* columns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_planned_therapies_excluded",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_planned_therapies_required",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_supportive_therapies_excluded",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_supportive_therapies_required",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_therapies_excluded",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_therapies_required",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_therapy_components_excluded",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_therapy_components_required",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_therapy_types_excluded",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trial",
            name="omop_therapy_types_required",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["omop_therapies_required", "omop_therapies_excluded"],
                name="idx_omop_therapies_pair_gin",
                opclasses=["jsonb_ops", "jsonb_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["omop_therapy_types_required", "omop_therapy_types_excluded"],
                name="idx_omop_therapy_types_gin",
                opclasses=["jsonb_ops", "jsonb_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=[
                    "omop_therapy_components_required",
                    "omop_therapy_components_excluded",
                ],
                name="idx_omop_therapy_comps_gin",
                opclasses=["jsonb_ops", "jsonb_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=[
                    "omop_supportive_therapies_required",
                    "omop_supportive_therapies_excluded",
                ],
                name="idx_omop_sup_therapies_gin",
                opclasses=["jsonb_ops", "jsonb_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=[
                    "omop_planned_therapies_required",
                    "omop_planned_therapies_excluded",
                ],
                name="idx_omop_planned_therapies_gin",
                opclasses=["jsonb_ops", "jsonb_ops"],
            ),
        ),
    ]
