# Generated by Django 5.2.7 on 2026-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0011_therapy_omop_concept_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OmopConcept",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "concept_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("concept_name", models.TextField()),
                ("vocabulary_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
