# Generated by Django 5.2.7 on 2026-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0012_omopconcept"),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyOmopMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("regimen", "regimen"),
                            ("component", "component"),
                            ("category", "category"),
                        ],
                        max_length=16,
                    ),
                ),
                ("cb_code", models.CharField(max_length=255)),
                (
                    "omop_concept_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("omop_name", models.TextField(blank=True, null=True)),
                ("omop_vocab", models.TextField(blank=True, null=True)),
                (
                    "match",
                    models.CharField(
                        choices=[
                            ("auto", "auto"),
                            ("curated", "curated"),
                            ("llm", "llm"),
                            ("needs_review", "needs_review"),
                            ("no_omop", "no_omop"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["match"], name="idx_therapy_omop_map_match")
                ],
                "unique_together": {("level", "cb_code")},
            },
        ),
    ]
