# Generated by Django 5.2.7 on 2026-07-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0013_therapyomopmapping'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trial',
            name='idx_omop_therapy_types_gin',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='omop_therapy_types_excluded',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='omop_therapy_types_required',
        ),
        migrations.AlterField(
            model_name='therapycomponentcategory',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP concept_id for this drug class (pinned CTOMOP release); null when unmapped.', null=True),
        ),
    ]
