# Generated by Django 5.2.7 on 2026-07-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False  # DROP INDEX CONCURRENTLY cannot run inside a transaction

    dependencies = [
        ('trials', '0013_therapyomopmapping'),
    ]

    operations = [
        # Use CONCURRENTLY to avoid ACCESS EXCLUSIVE lock on the Trial table.
        # atomic=False is required (CONCURRENTLY is forbidden inside transactions).
        migrations.RunSQL(
            sql='DROP INDEX CONCURRENTLY IF EXISTS idx_omop_therapy_types_gin',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='trial',
            name='omop_therapy_types_excluded',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='omop_therapy_types_required',
        ),
        migrations.AlterField(
            model_name='therapycomponentcategory',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP concept_id for this drug class (pinned CTOMOP release); null when unmapped.', null=True),
        ),
    ]
