# Generated by Django 5.2.7 on 2026-07-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0014_merge_omop_concept_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategoryOmopLookup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('component_concept_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category_codes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
