# Generated by Django 5.2.7 on 2026-07-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0013_trial_omop_intervention_concept_ids'),
        ('trials', '0014_drop_omop_therapy_types_columns'),
    ]

    operations = [
    ]
