# Generated by Django 5.2.7 on 2026-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0015_componentcategoryomoplookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapyomopmapping',
            name='match',
            field=models.CharField(choices=[('auto', 'auto'), ('curated', 'curated'), ('llm', 'llm'), ('needs_review', 'needs_review'), ('no_omop', 'no_omop'), ('crosswalk_only', 'crosswalk_only'), ('deferred', 'deferred')], max_length=16),
        ),
    ]
