# Generated by Django 5.2.7 on 2026-07-21 14:44

from django.db import migrations, models


def clear_stale_category_concept_ids(apps, schema_editor):
    """Null the now-dead TherapyComponentCategory.omop_concept_id (decision A, #4502).

    Envs where the previous loader ran with the old CSV have class concept_ids
    stored here. The field is now declared unused (nothing reads it: the mapper
    dropped the category level and the trial omop_therapy_types_* columns are
    gone), so clear the stale values to match the contract. Idempotent no-op where
    already null. Reverse is a noop — the concept_ids would be re-derived from the
    CSV by the loader, and the category rows are audit-only in that CSV.
    """
    Category = apps.get_model('trials', 'TherapyComponentCategory')
    # Scope to the DB being migrated (split-DB: don't let the router divert the write).
    Category.objects.using(schema_editor.connection.alias).exclude(
        omop_concept_id__isnull=True
    ).update(omop_concept_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0016_alter_therapyomopmapping_match'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trial',
            name='idx_omop_therapy_types_gin',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='omop_therapy_types_excluded',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='omop_therapy_types_required',
        ),
        migrations.AlterField(
            model_name='therapycomponentcategory',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="Unused: drug-class 'types' are not OMOP-mapped (EXACT ADR 0001 decision A, #4502). Types resolve via the component concept_id -> category code lookup (#4503), not a class concept_id.", null=True),
        ),
        migrations.RunPython(
            clear_stale_category_concept_ids,
            migrations.RunPython.noop,
        ),
    ]
