# Generated by Django 5.2.7 on 2026-07-21 20:36

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0017_remove_trial_idx_omop_therapy_types_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnicity',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP race concept_id (CTOMOP) for this ethnicity value; null when unmapped.', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='omop_ethnicity_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='omop_gender_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=django.contrib.postgres.indexes.GinIndex(fields=['omop_ethnicity_required'], name='idx_omop_ethnicity_req_gin', opclasses=['jsonb_ops']),
        ),
    ]
