# Generated by Django 5.2.7 on 2026-07-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0018_ethnicity_omop_concept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethnicity',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP race concept_id (PROMOP) for this ethnicity value; null when unmapped.', null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP concept_id for this code (pinned PROMOP release); null when the regimen has no clean standard concept and is expanded into its components/classes at backfill. Source for the trial omop_* columns.', null=True),
        ),
        migrations.AlterField(
            model_name='therapycomponent',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP concept_id for this drug component (pinned PROMOP release); null when unmapped. Source for the trial omop_therapy_components_* columns.', null=True),
        ),
    ]
