# Generated by Django 5.2.7 on 2026-07-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0019_rename_ctomop_to_promop_help_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentCategoryOmopLookup',
        ),
    ]
