# Generated by Django 5.2.7 on 2026-08-03 12:52

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0020_delete_componentcategoryomoplookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='omop_therapy_types_excluded',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='omop_therapy_types_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=django.contrib.postgres.indexes.GinIndex(fields=['omop_therapy_types_required', 'omop_therapy_types_excluded'], name='idx_omop_therapy_types_gin', opclasses=['jsonb_ops', 'jsonb_ops']),
        ),
    ]
