# Generated by Django 5.2.7 on 2026-08-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0021_readd_omop_therapy_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='largest_lymph_node_size_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='spleen_size_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
