# Generated by Django 5.2.7 on 2026-09-28 21:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0022_trial_largest_lymph_node_size_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP (SNOMED Language) concept_id for this language; null when unmapped.', null=True),
        ),
        migrations.AddField(
            model_name='languageskilllevel',
            name='omop_concept_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='OMOP (HK-Language) concept_id for this capability; null when unmapped.', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='omop_languages_skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=django.contrib.postgres.indexes.GinIndex(fields=['omop_languages_skills_required'], name='idx_omop_lang_skills_req_gin', opclasses=['jsonb_ops']),
        ),
    ]
