# Generated by Django 5.2.7 on 2026-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0022_trial_largest_lymph_node_size_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CytogenicMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.TextField(db_index=True, unique=True)),
                ('title', models.TextField(db_index=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MolecularMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.TextField(db_index=True, unique=True)),
                ('title', models.TextField(db_index=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        # AlterUniqueTogether MUST precede the RemoveFields it references —
        # the autodetector emits it last, which blows up with
        # "MarkerCategoryConnection has no field named 'marker'" when the
        # migration is replayed (test-DB build, fresh install).
        migrations.AlterUniqueTogether(
            name='markercategoryconnection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='marker',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='markercategoryconnection',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='markercategoryconnection',
            name='category',
        ),
        migrations.RemoveIndex(
            model_name='trial',
            name='idx_omop_intervention_cids_gin',
        ),
        migrations.RemoveField(
            model_name='rawdataitem',
            name='extracted_data',
        ),
        migrations.RemoveField(
            model_name='rawdataitem',
            name='old_raw_data',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='omop_intervention_concept_ids',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='MarkerCategory',
        ),
        migrations.DeleteModel(
            name='MarkerCategoryConnection',
        ),
    ]
