# Generated by Django 5.2.7 on 2026-08-10 00:22

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0022_trial_largest_lymph_node_size_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('projection_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vocab_release_id', models.CharField(max_length=64)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('manifest_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('disabled', models.BooleanField(default=False)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published', 'disabled'], name='idx_proj_release_state'), models.Index(fields=['vocab_release_id'], name='idx_proj_release_vocab')],
            },
        ),
        migrations.CreateModel(
            name='ProjectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_code', models.CharField(max_length=255)),
                ('omop_therapy_types_required', models.JSONField(blank=True, default=list)),
                ('omop_therapy_types_excluded', models.JSONField(blank=True, default=list)),
                ('projection', models.ForeignKey(db_column='projection_id', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trials.projectionrelease')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['omop_therapy_types_required'], name='idx_proj_snap_req_gin'), django.contrib.postgres.indexes.GinIndex(fields=['omop_therapy_types_excluded'], name='idx_proj_snap_exc_gin')],
                'constraints': [models.UniqueConstraint(fields=('projection', 'trial_code'), name='uq_projection_snapshot_trial')],
            },
        ),
    ]
