# Generated by Django 5.2.7 on 2026-08-14 14:37

from django.db import migrations


class Migration(migrations.Migration):
    """Drop catalog models EXACT declares but never reads.

    Nothing in EXACT queries RawDataItem, TrialUniverse or TrialUniverseEntry —
    they only existed in models.py and the initial migration. Declaring a model
    EXACT doesn't read still costs: the CB-derived catalogs we deploy against
    prune those tables (the Harvard extract DROPs trials_rawdataitem,
    trials_trialuniverse and trials_trialuniverseentry outright), so keeping the
    models would leave the schema-subset invariant unsatisfiable there.

    Irreversible in practice on single-database installs: reversing restores
    the tables but not their contents. CB keeps all three; a subset is still a
    subset.
    """

    dependencies = [
        ('trials', '0023_align_with_cb_catalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawDataItem',
        ),
        # AlterUniqueTogether must precede the RemoveFields it references —
        # same autodetector ordering trap as 0023.
        migrations.AlterUniqueTogether(
            name='trialuniverseentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trialuniverseentry',
            name='universe',
        ),
        migrations.RemoveField(
            model_name='trialuniverseentry',
            name='trial',
        ),
        migrations.DeleteModel(
            name='TrialUniverse',
        ),
        migrations.DeleteModel(
            name='TrialUniverseEntry',
        ),
    ]
