# Generated by Django 5.2.7 on 2026-08-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0024_drop_unused_catalog_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cytogenicmarker',
            options={'verbose_name': 'cytogenetic marker', 'verbose_name_plural': 'cytogenetic markers'},
        ),
    ]
