"""Central trial-type taxonomy: which trial types apply to which diseases.

Single source of truth for the (code, title, disease applicability) mapping.
Used by the seed migration (`0005_seed_trial_taxonomy`) to populate
`TrialType` rows and `TrialTypeDiseaseConnection` records.

Each entry is `(code, title, diseases)` where `diseases` is the list of
disease codes the trial type applies to (matched case-insensitively against
`Disease.code`). Categories are grouped for readability only — they have no
runtime meaning; the seed migration flattens via `ALL_TRIAL_TYPES`.
"""

TRIAL_TAXONOMY: dict[str, list[tuple[str, str, list[str]]]] = {
    'treatment': [
        ('chemotherapy', 'Chemotherapy', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('targeted_therapy_pi3k_inhibitors', 'Targeted Therapy: PI3K Inhibitors', ['FL', 'MM', 'BC']),
        ('targeted_therapy_btk_inhibitors', 'Targeted Therapy: BTK Inhibitors', ['FL', 'CLL', 'MCL']),
        ('targeted_therapy_bcl2_inhibitors', 'Targeted Therapy: BCL2 Inhibitors', ['FL', 'MM', 'CLL', 'MCL']),
        ('targeted_therapy_proteasome_inhibitors', 'Targeted Therapy: Proteasome Inhibitors', ['MM', 'MCL']),
        ('targeted_therapy_imids', 'Targeted Therapy: IMiDs (Immunomodulatory Drugs)', ['FL', 'MM', 'CLL', 'MCL']),
        ('targeted_therapy_cdk46_inhibitors', 'Targeted Therapy: CDK4/6 Inhibitors', ['BC', 'MCL']),
        ('targeted_therapy_parp_inhibitors', 'Targeted Therapy: PARP Inhibitors', ['BC']),
        ('targeted_therapy_her2_inhibitors', 'Targeted Therapy: HER2 Inhibitors', ['BC']),
        ('targeted_therapy_other', 'Targeted Therapy: Other', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('immunotherapy_monoclonal_antibodies', 'Immunotherapy: Monoclonal Antibodies', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('immunotherapy_bispecific_antibodies', 'Immunotherapy: Bispecific Antibodies', ['FL', 'MM', 'CLL', 'MCL']),
        ('immunotherapy_antibody_drug_conjugates', 'Immunotherapy: Antibody-Drug Conjugates', ['FL', 'MM', 'BC', 'MCL']),
        ('immunotherapy_checkpoint_inhibitors', 'Immunotherapy: Checkpoint Inhibitors', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('immunotherapy_other', 'Immunotherapy: Other', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('cellular_therapy_car_t', 'Cellular Therapy: CAR-T', ['FL', 'MM', 'CLL', 'MCL']),
        ('cellular_therapy_other', 'Cellular Therapy: Other', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('stem_cell_transplant_autologous', 'Stem Cell Transplant: Autologous', ['FL', 'MM', 'MCL']),
        ('stem_cell_transplant_allogeneic', 'Stem Cell Transplant: Allogeneic', ['FL', 'MM', 'CLL', 'MCL']),
        ('radiation_therapy', 'Radiation Therapy', ['FL', 'MM', 'BC', 'MCL']),
        ('surgery', 'Surgery', ['BC']),
        ('hormone_therapy', 'Hormone Therapy', ['BC']),
        ('endocrine_therapy', 'Endocrine Therapy', ['BC']),
        ('combination_therapy', 'Combination Therapy', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('maintenance_therapy', 'Maintenance Therapy', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('consolidation_therapy', 'Consolidation Therapy', ['FL', 'MM', 'CLL', 'MCL']),
        ('induction_therapy', 'Induction Therapy', ['FL', 'MM', 'CLL', 'MCL']),
        ('neoadjuvant_therapy', 'Neoadjuvant Therapy', ['BC']),
        ('adjuvant_therapy', 'Adjuvant Therapy', ['BC']),
        ('salvage_therapy', 'Salvage Therapy', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('palliative_therapy', 'Palliative Therapy', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('watchful_waiting', 'Watchful Waiting / Observation', ['FL', 'CLL', 'MCL']),
        ('experimental_drug', 'Experimental Drug', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('drug_repurposing', 'Drug Repurposing', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('other_treatment', 'Other Treatment', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
    ],
    'prevention': [
        ('cancer_prevention', 'Cancer Prevention', ['CLL', 'BC', 'MCL']),
        ('recurrence_prevention', 'Recurrence Prevention', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('risk_reduction_intervention', 'Risk-Reduction Intervention', ['MM', 'BC']),
        ('vaccine_prevention', 'Vaccine Prevention', ['CLL', 'BC', 'MCL']),
        ('lifestyle_behavioral_prevention', 'Lifestyle / Behavioral Prevention', ['BC']),
        ('genetic_risk_prevention', 'Genetic-Risk Prevention', ['BC']),
        ('infection_prevention', 'Infection Prevention', ['FL', 'MM', 'CLL', 'MCL']),
        ('brca_carriers_recurrence_prevention', 'BRCA Carriers Recurrence-prevention', ['BC']),
        ('brca_carriers_risk_reduction', 'BRCA Carriers Risk reduction', ['BC']),
    ],
    'diagnostic': [
        ('imaging', 'Imaging', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('genetic_testing', 'Genetic Testing', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('biomarker_testing', 'Biomarker Testing', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('molecular_profiling', 'Molecular Profiling', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('pathology_tissue_testing', 'Pathology / Tissue Testing', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('mrd_testing', 'Minimal Residual Disease (MRD) Testing', ['FL', 'MM', 'CLL', 'MCL']),
        ('brca_testing', 'BRCA Testing', ['BC']),
        ('early_detection_testing', 'Early Detection Testing', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('mutation_testing_profiling_sequencing', 'Mutation Testing/Profiling/Sequencing', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('diagnostic_procedure_evaluation', 'Diagnostic Procedure Evaluation', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('ctdna_testing', 'ctDNA Testing', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('ai_assisted_diagnosis', 'AI-Assisted Diagnosis', ['BC']),
    ],
    'screening': [
        ('cancer_screening', 'Cancer Screening', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('early_detection', 'Early Detection', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('imaging_based_screening', 'Imaging-Based Screening', ['MM', 'BC']),
        ('biomarker_based_screening', 'Biomarker-Based Screening', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('genetic_risk_screening', 'Genetic Risk Screening', ['MM', 'BC']),
        ('recurrence_monitoring_surveillance', 'Recurrence Monitoring / Surveillance', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('brca_carriers_surveillance_early_detection', 'BRCA Carriers Surveillance/Early Detection', ['BC']),
        ('ctdna_based_screening', 'ctDNA-Based Screening', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
    ],
    'supportive_care': [
        ('symptom_management', 'Symptom Management', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('managing_side_effects', 'Managing Side Effects', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('supportive_therapy', 'Supportive Therapy', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('palliative_quality_of_life_care', 'Palliative / Quality-of-Life Care', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('infection_prevention_immune_support', 'Infection Prevention & Immune Support', ['FL', 'MM', 'CLL', 'MCL']),
        ('physical_rehabilitation', 'Physical Rehabilitation', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('physical_activity_exercise', 'Physical Activity/Exercise', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('fertility_reproductive_health', 'Fertility / Reproductive Health', ['FL', 'CLL', 'BC', 'MCL']),
        ('psychosocial_support', 'Psychosocial Support', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('nutritional_support', 'Nutritional Support', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('support_education', 'Support / Education', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('complementary_integrative_medicine', 'Complementary / Integrative Medicine', ['BC']),
    ],
    'health_services_research': [
        ('decision_making', 'Decision-Making', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('telehealth_remote_care', 'Telehealth / Remote Care', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('care_delivery_model', 'Care Delivery Model', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('access_to_care', 'Access to Care', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('clinical_trials_access', 'Clinical Trials Access', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('real_world_care_pathways', 'Real-World Care Pathways', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('cost_of_care', 'Cost of Care', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('patient_education', 'Patient Education', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('adherence_compliance', 'Adherence / Compliance', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('health_equity_disparities', 'Health Equity / Disparities', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('quality_improvement', 'Quality Improvement', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('resource_utilization', 'Resource Utilization', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
    ],
    'basic_science': [
        ('biomarker_discovery', 'Biomarker Discovery', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('tumor_biology_study', 'Tumor Biology Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('immune_mechanism_study', 'Immune Mechanism Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('pharmacodynamic_study', 'Pharmacodynamic Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('pharmacokinetic_study', 'Pharmacokinetic Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('resistance_mechanism_study', 'Resistance Mechanism Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('genomic_molecular_characterization', 'Genomic / Molecular Characterization', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('tissue_blood_collection_study', 'Tissue / Blood Collection Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
    ],
    'device_feasibility': [
        ('surgical_device_feasibility', 'Surgical Device Feasibility', ['BC']),
        ('radiation_device_feasibility', 'Radiation Device Feasibility', ['FL', 'BC', 'MCL']),
        ('imaging_device_feasibility', 'Imaging Device Feasibility', ['MM', 'BC']),
        ('monitoring_device_feasibility', 'Monitoring Device Feasibility', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('diagnostic_device_feasibility', 'Diagnostic Device Feasibility', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('wearable_digital_health_device', 'Wearable / Digital Health Device', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('drug_delivery_device', 'Drug Delivery Device', ['MM', 'BC']),
        ('procedure_guidance_device', 'Procedure-Guidance Device', ['BC']),
    ],
    'other': [
        ('observational_study', 'Observational Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('retrospective_study', 'Retrospective Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('registry', 'Registry', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('survey_interview', 'Survey / Interview', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('feasibility_pilot_study', 'Feasibility / Pilot Study', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
        ('other_trial_type', 'Other', ['FL', 'MM', 'CLL', 'BC', 'MCL']),
    ],
}

# Flat list of all (code, title, diseases) triples, deduplicated by code, sorted by title.
ALL_TRIAL_TYPES: list[tuple[str, str, list[str]]] = sorted(
    {(code, title, tuple(diseases)) for types in TRIAL_TAXONOMY.values() for code, title, diseases in types},
    key=lambda x: x[1],
)
