# Generated by Django 5.2.7 on 2026-07-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.BigIntegerField()),
                ('concept_id', models.IntegerField()),
                ('concept_name', models.CharField(max_length=255)),
                ('domain_id', models.CharField(max_length=20)),
                ('vocabulary_id', models.CharField(max_length=20)),
                ('concept_class_id', models.CharField(max_length=20)),
                ('standard_concept', models.CharField(blank=True, max_length=1, null=True)),
                ('concept_code', models.CharField(max_length=50)),
                ('valid_start_date', models.DateField(blank=True, null=True)),
                ('valid_end_date', models.DateField(blank=True, null=True)),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['release_id', 'vocabulary_id'], name='ix_mconcept_rel_vocab')],
                'constraints': [models.UniqueConstraint(fields=('release_id', 'concept_id'), name='uq_mconcept_rel_cid')],
            },
        ),
        migrations.CreateModel(
            name='MirrorConceptAncestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.BigIntegerField()),
                ('ancestor_concept_id', models.IntegerField()),
                ('descendant_concept_id', models.IntegerField()),
                ('min_levels_of_separation', models.IntegerField()),
                ('max_levels_of_separation', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['release_id', 'ancestor_concept_id'], name='ix_mca_rel_anc'), models.Index(fields=['release_id', 'descendant_concept_id'], name='ix_mca_rel_desc')],
            },
        ),
        migrations.CreateModel(
            name='MirrorConceptRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.BigIntegerField()),
                ('concept_id_1', models.IntegerField()),
                ('concept_id_2', models.IntegerField()),
                ('relationship_id', models.CharField(max_length=20)),
                ('valid_start_date', models.DateField(blank=True, null=True)),
                ('valid_end_date', models.DateField(blank=True, null=True)),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['release_id', 'concept_id_1', 'relationship_id'], name='ix_mcr_rel_c1_rid'), models.Index(fields=['release_id', 'concept_id_2', 'relationship_id'], name='ix_mcr_rel_c2_rid')],
            },
        ),
        migrations.CreateModel(
            name='MirrorVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.BigIntegerField()),
                ('vocabulary_id', models.CharField(max_length=20)),
                ('vocabulary_name', models.CharField(max_length=255)),
                ('vocabulary_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('vocabulary_version', models.CharField(blank=True, max_length=255, null=True)),
                ('vocabulary_concept_id', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('release_id', 'vocabulary_id'), name='uq_mvocab_rel_vocab')],
            },
        ),
    ]
