# Generated by Django 5.2.7 on 2026-07-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_mirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.BigIntegerField(unique=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('staging', 'staging'), ('ready', 'ready'), ('active', 'active'), ('superseded', 'superseded'), ('failed', 'failed')], db_index=True, default='staging', max_length=16)),
                ('row_counts', models.JSONField(blank=True, default=dict)),
                ('checksums', models.JSONField(blank=True, default=dict)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('state',), name='uq_one_active_mirror_release')],
            },
        ),
    ]
