# Generated by Django 5.2.7 on 2026-07-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_mirror', '0002_mirrorrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategoryOmopLookup',
            fields=[
                ('component_concept_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentLookupStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, unique=True)),
                ('release_id', models.BigIntegerField()),
                ('built_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
