# Generated by Django 5.2.7 on 2026-08-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab_mirror", "0004_populate_component_category_lookup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectionAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_id", models.BigIntegerField(unique=True)),
                ("run_id", models.CharField(blank=True, default="", max_length=255)),
                ("trial_count", models.IntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, default="", max_length=128)),
                ("issued_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
